MVCKÜTÜPHANE/Controllers/ÜyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCKÜTÜPHANE.Models;
using MVCKÜTÜPHANE.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MVCKÜTÜPHANE.Controllers
{
    public class ÜyeController : Controller
    {
        // GET: Üye
        DBKütüphaneEntities db = new DBKütüphaneEntities();
        public ActionResult Index(int sayfa=1)
        {
            var deger = db.Tbl_Üye.ToList().ToPagedList(sayfa, 4);
            return View(deger);
 
        }

        [HttpGet]
        public ActionResult ÜyeEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ÜyeEkle(Tbl_Üye p)
        {
            if (!ModelState.IsValid)
            {
                return View("ÜyeEkle");
            }
            db.Tbl_Üye.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ÜyeSil(int id)
        {
            var üye = db.Tbl_Üye.Find(id);
            db.Tbl_Üye.Remove(üye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ÜyeGetir(int id)
        {
            var üye1 = db.Tbl_Üye.Find(id);
            return View("ÜyeGetir", üye1);
        }

        public ActionResult ÜyeGüncelle(Tbl_Üye ü)
        {
            var üye2 = db.Tbl_Üye.Find(ü.ÜyeID);
            üye2.AD = ü.AD;
            üye2.SOYAD = ü.SOYAD;
            üye2.MAİL = ü.MAİL;
            üye2.KULLANICIADI = ü.KULLANICIADI;
            üye2.ŞİFRE = ü.ŞİFRE;
            üye2.FOTOĞRAF = ü.FOTOĞRAF;
            üye2.TELEFON = ü.TELEFON;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVCKÜTÜPHANE/Views/Üye/Index.cshtml
@using MVCKÜTÜPHANE.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Tbl_Üye>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<title> Üye Sayfası</title>
<br />
<br />


    <h2>Üyeler</h2>

<br />
<br />
<br />
<br />
<br />

<div>
    <table class="table table-bordered">
        <tr>
            <th> Üye ID</th>
            <th> Üye ADI</th>
            <th> Üye Soyadı</th>
            <th> Mail</th>
            <th> Kullanıcı Adı</th>
            <th> Kullanıcı Şifre</th>
            <th> Kullanıcı Telefon</th>
            <th> SİL</th>
            <th> GÜNCELLE</th>
        </tr>
        @foreach (var value in Model)
        {

            <tr>
                <td> @value.ÜyeID</td>
                <td> @value.AD</td>
                <td> @value.SOYAD</td>
                <td> @value.MAİL</td>
                <td> @value.KULLANICIADI</td>
                <td> @value.ŞİFRE</td>
                <td> @value.TELEFON</td>
                <td><a href="/Üye/ÜyeSil/ @value.ÜyeID" class="btn btn-outline-danger">Sil</a></td>
                <td><a href="/Üye/ÜyeGetir/ @value.ÜyeID" class="btn btn-outline-success">Güncelle</a></td>

            </tr>
        }

    </table>
</div>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
<a href="/Üye/ÜyeEkle/" class="btn btn-outline-primary"> Yeni Üye Ekle</a>

MVCKÜTÜPHANE/Views/Üye/ÜyeEkle.cshtml
@model MVCKÜTÜPHANE.Models.Entity.Tbl_Üye
@{
    ViewBag.Title = "ÜyeEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<title> Üye Ekleme Sayfası</title>

<h2>Üye Ekleme Sayfası</h2>
<form class="form-group" method="post">
    <div>
        <label> Üye Adı</label>
        @Html.TextBoxFor(p => p.AD, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.AD, "", new { @style = "color:red" })
        <br />
        <label> Üye Soyadı</label>
        @Html.TextBoxFor(p => p.SOYAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x=>x.SOYAD)
        <br />
        <label> Üye Mail</label>
        @Html.TextBoxFor(p => p.MAİL, new { @class = "form-control" })
        <br />
        <label> Kullanıcı Adı</label>
        @Html.TextBoxFor(p => p.KULLANICIADI, new { @class = "form-control" })
        <br />
        <label> Kullanıcı Şifre</label>
        @Html.TextBoxFor(p => p.ŞİFRE, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.ŞİFRE, "", new { @style = "color:red" })
        <br />
        <label> Fotoğraf</label>
        @Html.TextBoxFor(p => p.FOTOĞRAF, new { @class = "form-control" })
        <br />
        <label> Telefon </label>
        @Html.TextBoxFor(p => p.TELEFON, new { @class = "form-control" })
        <br />
        <button class="btn btn-outline-primary">Ekle</button>
    </div>
</form>

MVCKÜTÜPHANE/Views/Üye/ÜyeGetir.cshtml
@model MVCKÜTÜPHANE.Models.Entity.Tbl_Üye
@{
    ViewBag.Title = "ÜyeGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<title> Üye Güncelleme Sayfası</title>

<h2>Üye Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("ÜyeGüncelle", "Üye", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.ÜyeID)
        @Html.TextBoxFor(x => x.ÜyeID, new { @class = "form-control" })
        <br />
        <label> Üye Adı:</label>
        @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
        <br />
        <label> Üye Soyadı:</label>
        @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })
        <br />
        <label> Mail:</label>
        @Html.TextBoxFor(x => x.MAİL, new { @class = "form-control" })
        <br />
        <label> Kullanıcı Adı:</label>
        @Html.TextBoxFor(x => x.KULLANICIADI, new { @class = "form-control" })
        <br />
        <label> Kullanıcı Şifre:</label>
        @Html.TextBoxFor(x => x.ŞİFRE, new { @class = "form-control" })
        <br />
        <label> Foroğraf:</label>
        @Html.TextBoxFor(x => x.FOTOĞRAF, new { @class = "form-control" })
        <br />
        <label> Telefon:</label>
        @Html.TextBoxFor(x => x.TELEFON, new { @class = "form-control" })
        <br />
        <button class="btn btn-outline-success"> Güncelle </button>
    </div>
}