MVCKÜTÜPHANE/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCKÜTÜPHANE.Models.Entity;

namespace MVCKÜTÜPHANE.Controllers
{
    public class YazarController : Controller
    {
        // GET: Yazar
        DBKütüphaneEntities db = new DBKütüphaneEntities();
        public ActionResult Index(string y)
        {
            var yazar = from yz in db.Tbl_Yazar select yz;
            if (!string.IsNullOrEmpty(y))
            {
                yazar = yazar.Where(z => z.AD.Contains(y));
            }
            return View(yazar.ToList());
        }
        [HttpGet]
        public ActionResult YazarEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YazarEkle(Tbl_Yazar y)
        {
            if (!ModelState.IsValid)
            {
                return View("YazarEkle");
            }
            var yzr = db.Tbl_Yazar.Add(y);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YazarSil(int id)
        {
            var yzrsil = db.Tbl_Yazar.Find(id);
            db.Tbl_Yazar.Remove(yzrsil);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult YazarGüncelle(int id)
        {
            var yzr=db.Tbl_Yazar.Find(id);
            return View("YazarGüncelle",yzr);
        }
        [HttpPost]
        public ActionResult YazarGüncelle(Tbl_Yazar yz)
        {
            var yzrgün = db.Tbl_Yazar.Find(yz.YazarID);
            yzrgün.AD = yz.AD;
            yzrgün.SOYAD = yz.SOYAD;
            yzrgün.Detay = yz.Detay;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult YazarınKitapları(int id)
        {
            var yazar = db.Tbl_Kitap.Where(x => x.YAZAR == id).ToList();
            var yzrad = db.Tbl_Yazar.Where(y => y.YazarID == id).Select(y => y.AD + " " + y.SOYAD).FirstOrDefault();
            ViewBag.yzad = yzrad;
            return View(yazar);
            
        }


    }
}

MVCKÜTÜPHANE/Views/Yazar/Index.cshtml
@using MVCKÜTÜPHANE.Models.Entity
@model List<Tbl_Yazar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<title>Yazar Sayfası</title>

    <h2>Yazarlar</h2>

@using (Html.BeginForm("Index", "Yazar", FormMethod.Get))
{
    <div style="margin-bottom:15px;margin-top:15px">
        <b>Aranacak Yazar Adı:</b> <br />@Html.TextBox("y")
        <input type="submit" value="Ara" />
    </div>
}

<br />
<br />
<br />
<br />

<table class="table table-bordered">
    <tr>
        <th>Yazar ID</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>Detay</th>
        <th>Sil</th>
        <th> Güncelle</th>
    </tr>
    @foreach (var y in Model)
    {
        <tr>
            <td>@y.YazarID</td>
            <td>@y.AD</td>
            <td>@y.SOYAD</td>
            <td>@y.Detay</td>
            <td><a href="/Yazar/YazarSil/@y.YazarID" class="btn btn-outline-danger">Sil</a></td>
            <td><a href="/Yazar/YazarGüncelle/@y.YazarID" class="btn btn-outline-success">Güncelle</a></td>
        </tr>
    }
</table>
<br />
<a href="/Yazar/YazarEkle/" class="btn btn-outline-primary">Yazar Ekle</a>

MVCKÜTÜPHANE/Views/Yazar/YazarEkle.cshtml
@model MVCKÜTÜPHANE.Models.Entity.Tbl_Yazar
@{
    ViewBag.Title = "YazarEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<title> Yazar Ekleme Sayfası </title>
<h2>Yazar Ekle</h2>

<form class="form-group" method="post">

    <div>
        <label> Yazar Adı:</label>
        @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x=>x.AD)
        <br />
        <label> Yazar Soyad:</label>
        @Html.TextBoxFor(y => y.SOYAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x=>x.SOYAD)
        <br />
        <label> Yazar Detay Bilgiler</label>
        @Html.TextAreaFor(y => y.Detay, new { @class = "form-control" })
        <br />
        <button class="btn btn-outline-primary"> Yazar Kaydet </button>
    </div>

</form>

MVCKÜTÜPHANE/Views/Yazar/YazarGüncelle.cshtml
@model MVCKÜTÜPHANE.Models.Entity.Tbl_Yazar
@{
    ViewBag.Title = "YazarGüncelle";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<title> Yazar Güncelleme Sayfası </title>
<div style="background-color:white">
    <h2>Yazar Güncelleme Sayfası</h2>
</div>
<br />
@using (Html.BeginForm("YazarGüncelle", "Yazar", FormMethod.Post))
{
    <label> Yazar ID</label>
    @Html.TextBoxFor(x => x.YazarID, new { @class = "form-control" })
    <br />
    <label> Yazar AD</label>
    @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
    <br />
    <label> Yazar SOYAD</label>
    @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })
    <br />
    <label> Yazar DETAY</label>
    @Html.TextAreaFor(x => x.Detay, new { @class = "form-control" })
    <br />
    <button class="btn btn-outline-primary">Güncelle</button>
}

MVCKÜTÜPHANE/Views/Yazar/YazarınKitapları.cshtml
@model List<MVCKÜTÜPHANE.Models.Entity.Tbl_Kitap>
@{
    ViewBag.Title = "YazarınKitapları";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Yazarın Kitapları</h2>
<br />
<br />
<h3>@ViewBag.yzad</h3>
<br />
<br />
<br />
<br />

<table class="table table-striped">
    
    <tr>
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kategori</th>
        <th>Yayınevi</th>
    </tr>
    @foreach(var item in Model)
            {
                <tr>
                    <td>@item.KitapID</td>
                    <td>@item.AD</td>
                    <td>@item.Tbl_Category.AD</td>
                    <td>@item.YAYINEVİ</td>
                </tr>
            }

</table>