MVCKÜTÜPHANE/Controllers/AdminLoginController.cs
using MVCKÜTÜPHANE.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCKÜTÜPHANE.Models;
using System.Web.Security;

namespace MVCKÜTÜPHANE.Controllers
{
    public class AdminLoginController : Controller
    {
        // GET: AdminLogin
        DBKütüphaneEntities db = new DBKütüphaneEntities();

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Tbl_Admin a)
        {
            var login = db.Tbl_Admin.FirstOrDefault(x => x.AdminMail == a.AdminMail && x.AdminŞifre == a.AdminŞifre);
            if(login != null) 
            {
                FormsAuthentication.SetAuthCookie(login.AdminMail, false);
                Session["AdminMail"] = login.AdminMail.ToString();
                return RedirectToAction("Index", "AdminMainPage");

            }
            else
            {
                return View();
            }
           
        }
    }
}

MVCKÜTÜPHANE/Views/AdminLogin/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Giriş Yap</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Template/Login_v2/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Template/Login_v2/css/main.css">
    <!--===============================================================================================-->
</head>
<body>
    @using (Html.BeginForm("Index", "AdminLogin", FormMethod.Post)) {
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form method="post">
                    <span class="login100-form-title p-b-26">
                        Hoş Geldin
                    </span>

                    <div class="wrap-input100 validate-input" data-validate="Valid email is: a@b.c">
                        <input class="input100" type="text" name="AdminMail">
                        <span class="focus-input100" data-placeholder="MAİL"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Enter password">
                        <span class="btn-show-pass">
                            <i class="zmdi zmdi-eye"></i>
                        </span>
                        <input class="input100" type="password" name="AdminŞifre">
                        <span class="focus-input100" data-placeholder="ŞİFRE"></span>
                    </div>

                    <div class="container-login100-form-btn">
                        <div class="wrap-login100-form-btn">
                            <div class="login100-form-bgbtn"></div>
                            <button class="login100-form-btn">
                                Giriş Yap
                            </button>
                        </div>
                    </div>

                    <div class="text-center p-t-115">
                        <span class="txt1">
                            Hesabınız Yok mu?
                        </span>

                        
                    </div>
                </form>
            </div>
        </div>
    </div>
    }


    <div id="dropDownSelect1"></div>

    <!--===============================================================================================-->
    <script src="~/Template/Login_v2/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Template/Login_v2/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Template/Login_v2/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Template/Login_v2/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Template/Login_v2/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Template/Login_v2/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/Template/Login_v2/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/Template/Login_v2/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/Template/Login_v2/js/main.js"></script>

</body>
</html>